MOCK_INFORMATION_TABLE = """<?xml version="1.0" encoding="UTF-8"?>
<informationTable xmlns="http://www.sec.gov/edgar/document/thirteenf/informationtable">
  <infoTable><nameOfIssuer>APPLE INC</nameOfIssuer><titleOfClass>COM</titleOfClass><cusip>037833100</cusip><value>5400000000</value><shrsOrPrnAmt><sshPrnamt>21500000</sshPrnamt><sshPrnamtType>SH</sshPrnamtType></shrsOrPrnAmt><investmentDiscretion>SOLE</investmentDiscretion><votingAuthority><Sole>21500000</Sole><Shared>0</Shared><None>0</None></votingAuthority></infoTable>
  <infoTable><nameOfIssuer>BANK OF AMERICA CORP</nameOfIssuer><titleOfClass>COM</titleOfClass><cusip>060505104</cusip><value>3200000000</value><shrsOrPrnAmt><sshPrnamt>68000000</sshPrnamt><sshPrnamtType>SH</sshPrnamtType></shrsOrPrnAmt><investmentDiscretion>SOLE</investmentDiscretion><votingAuthority><Sole>68000000</Sole><Shared>0</Shared><None>0</None></votingAuthority></infoTable>
  <infoTable><nameOfIssuer>CHEVRON CORP NEW</nameOfIssuer><titleOfClass>COM</titleOfClass><cusip>166764100</cusip><value>1700000000</value><shrsOrPrnAmt><sshPrnamt>11000000</sshPrnamt><sshPrnamtType>SH</sshPrnamtType></shrsOrPrnAmt><investmentDiscretion>SOLE</investmentDiscretion><votingAuthority><Sole>11000000</Sole><Shared>0</Shared><None>0</None></votingAuthority></infoTable>
  <infoTable><nameOfIssuer>SPDR S&amp;P 500 ETF TRUST</nameOfIssuer><titleOfClass>TR UNIT</titleOfClass><cusip>78462F103</cusip><value>900000000</value><shrsOrPrnAmt><sshPrnamt>1300000</sshPrnamt><sshPrnamtType>SH</sshPrnamtType></shrsOrPrnAmt><investmentDiscretion>SOLE</investmentDiscretion><votingAuthority><Sole>1300000</Sole><Shared>0</Shared><None>0</None></votingAuthority></infoTable>
  <infoTable><nameOfIssuer>INVESCO QQQ TRUST</nameOfIssuer><titleOfClass>UNIT SER 1</titleOfClass><cusip>46090E103</cusip><value>600000000</value><shrsOrPrnAmt><sshPrnamt>1000000</sshPrnamt><sshPrnamtType>SH</sshPrnamtType></shrsOrPrnAmt><investmentDiscretion>SOLE</investmentDiscretion><votingAuthority><Sole>1000000</Sole><Shared>0</Shared><None>0</None></votingAuthority></infoTable>
  <infoTable><nameOfIssuer>MICROSOFT CORP</nameOfIssuer><titleOfClass>COM</titleOfClass><cusip>594918104</cusip><value>450000000</value><shrsOrPrnAmt><sshPrnamt>900000</sshPrnamt><sshPrnamtType>SH</sshPrnamtType></shrsOrPrnAmt><putCall>PUT</putCall><investmentDiscretion>SOLE</investmentDiscretion><votingAuthority><Sole>0</Sole><Shared>0</Shared><None>900000</None></votingAuthority></infoTable>
</informationTable>"""
